[client]
toolbarMode = "minimal"
[ui]
hideTopBar = true
[theme]
base="light"
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
[server]
# Disable file system watcher to reduce open file descriptors under high concurrency
fileWatcherType = "none"
# Optional: keep headless for server environments
headless = true